// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rowWhichMax
IntegerVector rowWhichMax(NumericMatrix m);
RcppExport SEXP epic_rowWhichMax(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    __result = Rcpp::wrap(rowWhichMax(m));
    return __result;
END_RCPP
}
